[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
anyhow = "1.0.75"
itertools = "0.12.0"
test-log = { version = "0.2.13", default-features = false, features = [
  "trace",
] }
